name: Alpha reference test

on:
  push:
    paths:
      - '**.py'
      - 'tests/**'
  pull_request:
    paths:
      - '**.py'
      - 'tests/**'

jobs:
  alpha_test_against_ref:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest
